name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: yarn install, build, and test
      run: |
        mkdir ~/.aws && echo $aws_config && echo $aws_credentials
        echo $aws_config >> ~/.aws/config && echo $aws_credentials >> ~/.aws/credentials
        yarn 
        yarn build
        aws configure list
        ls ~/.aws/
        cat ~/.aws/config && cat ~/.aws/credentials
        aws s3 sync build/ s3://s3-semaphore
      env:
        CI: true
        aws_config: ${{secrets.aws_config}}
        aws_credentials: ${{secrets.aws_credentials}}
